'use strict';

module.exports = {
  SET_STATE: 'SET_STATE',
  REQUEST_PRODUCTS: 'REQUEST_PRODUCTS',
  REQUEST_PRODUCTS_SUCCESS: 'REQUEST_PRODUCTS_SUCCESS',
  REQUEST_PRODUCTS_ERROR: 'REQUEST_PRODUCTS_ERROR'
};
